<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FAQs</title>
    <link rel="stylesheet" href="./css/FAQs2.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="../css/file.css">
</head>
<body>
<header class="header">

<a class="logo"> <i class="fas fa-graduation-cap"></i>CollegCom</a>

<div id="menu-btn" class="fas fa-bars"></div>

<nav class="navbar">
<ul>
            <li><a href="../mainpage2/main.php">home</a></li>
            <li><a href="../download and up/html/course-2.php">courses</a>
            </li>
            <li><a>pages </a>
                <ul>
                    <li><a href="../AIU gpa calculator/index.php">GPA Calculeter</a></li>
                    <li><a href="../Faqs page/FAQs.php">FAQ</a></li>
                </ul>
            </li>
        </ul>
</nav>

</header>
    <section class="all">
        <h2 class="title">FAQs</h2>
        

            <section>
               
                <div class="faq">
                    <div class="question">
                        <h3> what is the maximum number ofcredits per semester ?</h3>

                <svg  width="15" hight="10" viewBox="0 0 42 25">
                <path d="M3 3L21 21L39 3 "stroke="white" stroke-width="7" stroke-linecap="round"/>
                </svg> 
                    </div>
                    <div class="answer">
                        <p>
                            18 credits, unless the student's GPA is over 3.0 in which case they can take up to 21 credits.

                        </p>
                    </div>
                </div>

                <div class="faq">
                    <div class="question">
                        <h3>How are grades determined in AIU ?</h3>

                <svg  width="15" hight="10" viewBox="0 0 42 25">
                <path d="M3 3L21 21L39 3 "stroke="white" stroke-width="7" stroke-linecap="round"/>
                </svg> 
                    </div>
                    <div class="answer">
                        <p>
                            Grades are typically determined by quizzes, midterms, final exams, papers, projects, class attendance, and class participation.

                        </p>
                    </div>
                </div>

               

                <div class="faq">
                    <div class="question">
                <h3>How many years is the IT program ?</h3>

                <svg  width="15" hight="10" viewBox="0 0 42 25">
                <path d="M3 3L21 21L39 3 "stroke="white" stroke-width="7" stroke-linecap="round"/>
                </svg> 
                    </div>
                    <div class="answer">
                        <p>
                            5 years and 169 credits in total.

                        </p>
                    </div>
                </div>


                

                <div class="faq">
                    <div class="question">
                        <h3>How can I drop my course ?</h3>

                <svg  width="15" hight="10" viewBox="0 0 42 25">
                <path d="M3 3L21 21L39 3 "stroke="white" stroke-width="7" stroke-linecap="round"/>
                </svg> 
                    </div>
                    <div class="answer">
                        <p>
                            You can drop your course through the system "Moodle" during the last week before the finals.

                        </p>
                    </div>
                </div> 


                <div class="faq">
                    <div class="question">
                        <h3>When can i do the national test ?</h3>

                 <svg  width="15" hight="10" viewBox="0 0 42 25">
                <path d="M3 3L21 21L39 3 "stroke="white" stroke-width="7" stroke-linecap="round"/>
                </svg> 
                    </div>
                    <div class="answer">
                        <p>
                            After completing 92% of the program.
                        </p>
                    </div>
                </div>

                <div class="faq">
                    <div class="question">
                        <h3>When can i take my junior project course ?</h3>

                <svg  width="15" hight="10" viewBox="0 0 42 25">
                <path d="M3 3L21 21L39 3 "stroke="white" stroke-width="7" stroke-linecap="round"/>
                </svg> 
                    </div>
                    <div class="answer">
                        <p>
                            After completing 100 credits + Academic writing and Research course
                        </p>
                    </div>
                </div>

                <div class="faq">
                    <div class="question">
                        <h3>When can i take my senior project course ?</h3>

                <svg  width="15" hight="10" viewBox="0 0 42 25">
                <path d="M3 3L21 21L39 3 "stroke="white" stroke-width="7" stroke-linecap="round"/>
                </svg> 
                    </div>
                    <div class="answer">
                        <p>
                            After completing 130 credits + Junior
                        </p>
                    </div>
                </div>


                    


            </section>
    </section>

    <script src="./FAQs.js"></script>

    
</body>
</html>